# Generated by Django 4.2.4 on 2023-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correo', models.CharField(max_length=200)),
                ('contra', models.CharField(max_length=200)),
                ('divisa', models.CharField(max_length=3)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
