# Generated by Django 4.2.4 on 2023-09-13 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transacciones', models.BigIntegerField()),
                ('total_dinero', models.FloatField()),
                ('tipo', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=200)),
                ('clave_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('balance', models.FloatField()),
                ('divisa', models.CharField(max_length=3)),
                ('clave_usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='subcategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_transacciones', models.BigIntegerField()),
                ('total_dinero', models.FloatField()),
                ('tipo', models.CharField(max_length=7)),
                ('nombre', models.CharField(max_length=200)),
                ('clave_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='transferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('divisa', models.CharField(max_length=3)),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(max_length=500)),
                ('clave_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField()),
                ('divisa', models.CharField(max_length=3)),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(max_length=500)),
                ('clave_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria')),
                ('clave_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cuenta')),
                ('clave_subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ingresado', models.FloatField()),
                ('objetivo_asignado', models.FloatField()),
                ('fecha_limite', models.DateField()),
                ('clave_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria')),
                ('clave_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cuenta')),
                ('clave_subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='limite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_gastado', models.FloatField()),
                ('limite_asignado', models.FloatField()),
                ('fecha_limite', models.DateField()),
                ('clave_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria')),
                ('clave_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cuenta')),
                ('clave_subcategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.subcategoria')),
            ],
        ),
    ]
