# Generated by Django 4.2.4 on 2023-09-13 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categoria_cuenta_subcategoria_transferencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transferencia',
            old_name='clave_origen',
            new_name='clave_cuenta',
        ),
        migrations.AddField(
            model_name='transferencia',
            name='tipo',
            field=models.CharField(default='envio', max_length=20),
        ),
    ]
