# Generated by Django 4.2.4 on 2023-09-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_clave_origen_transferencia_clave_cuenta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='tipo',
            field=models.CharField(default='Gasto', max_length=10),
        ),
    ]
