# Generated by Django 4.2.6 on 2023-10-08 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_limite_clave_subcategoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='limite',
            name='clave_cuenta',
        ),
        migrations.RemoveField(
            model_name='objetivo',
            name='clave_cuenta',
        ),
    ]
