# Generated by Django 4.2.6 on 2023-10-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_limite_clave_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limite',
            name='clave_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria'),
        ),
        migrations.AlterField(
            model_name='objetivo',
            name='clave_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.categoria'),
        ),
    ]
