# Generated by Django 4.2.6 on 2023-10-08 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_limite_clave_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limite',
            name='clave_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objetivo',
            name='clave_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.usuario'),
            preserve_default=False,
        ),
    ]
