# Generated by Django 4.2.4 on 2023-10-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_limite_clave_usuario_objetivo_clave_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='comentarios',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
