# Generated by Django 4.2.4 on 2023-11-07 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_transaccion_comentarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='contra',
        ),
    ]
