# Generated by Django 4.2.4 on 2023-11-16 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_usuario_contra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limite',
            old_name='limite_asignado',
            new_name='asignado',
        ),
        migrations.RenameField(
            model_name='limite',
            old_name='total_gastado',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='objetivo_asignado',
            new_name='asignado',
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='total_ingresado',
            new_name='total',
        ),
    ]
