# Generated by Django 4.2.4 on 2023-11-16 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_limite_asignado_limite_asignado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='limite',
            name='divisa',
            field=models.CharField(default='mxn', max_length=3),
        ),
        migrations.AddField(
            model_name='objetivo',
            name='divisa',
            field=models.CharField(default='mxn', max_length=3),
        ),
    ]
