# Generated by Django 4.2.4 on 2023-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_limite_divisa_objetivo_divisa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='foto',
            field=models.ImageField(default=0, upload_to='imagenes_transacciones'),
            preserve_default=False,
        ),
    ]
