# Generated by Django 4.2.4 on 2023-12-05 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_transaccion_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaccion',
            name='foto',
        ),
    ]
