# Generated by Django 4.2.4 on 2023-12-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_transaccion_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes_transacciones'),
        ),
    ]
