# Generated by Django 4.2.4 on 2023-12-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_cuotas_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotas',
            name='pendiente',
            field=models.CharField(default='SI', max_length=2),
        ),
    ]
